//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareSysProd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches_and_Department
    {
        public int branch_id { get; set; }
        public string Branch_department_Code { get; set; }
        public string Branch_department_name { get; set; }
    }
}
