//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareSysProd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int DocumentationId { get; set; }
        public int DocumentTypeId { get; set; }
        public string FileLocation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Documentation Documentation { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
