//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareSysProd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMap
    {
        public int DocumentMapId { get; set; }
        public int CategoriesId { get; set; }
        public int DocumentTypeId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public bool Mandatorie { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual Categories_Type Categories_Type { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
