//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareSysProd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentationProcess
    {
        public int DocumentationProcessId { get; set; }
        public string CIF { get; set; }
        public string ClientName { get; set; }
        public string Mobile { get; set; }
        public string Branch { get; set; }
        public string CustomerType { get; set; }
        public int CategoriesId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public Nullable<int> DocumentationId { get; set; }
        public string CreatedByUserId { get; set; }
        public string ApprovedByUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Categories_Type Categories_Type { get; set; }
        public virtual Categories_Type Categories_Type1 { get; set; }
    }
}
