//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareSysProd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RiskEventDBEntities : DbContext
    {
      
    
        
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Branches_and_Department> Branches_and_Department { get; set; }
        public virtual DbSet<Categories_Type> Categories_Type { get; set; }
        public virtual DbSet<DocumentationProcess> DocumentationProcesses { get; set; }
        public virtual DbSet<DocumentMap> DocumentMaps { get; set; }
    
        public virtual int DeleteUserfromRole(string userId, string roleId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserfromRole", userIdParameter, roleIdParameter);
        }
    
        public virtual ObjectResult<Get_RoleByID_Result> Get_RoleByID(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_RoleByID_Result>("Get_RoleByID", roleIdParameter);
        }
    
        public virtual ObjectResult<Get_RoleByID2_Result> Get_RoleByID2(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_RoleByID2_Result>("Get_RoleByID2", userIdParameter);
        }
    
        public virtual ObjectResult<GetUsers_RoleByID_Result> GetUsers_RoleByID(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_RoleByID_Result>("GetUsers_RoleByID", roleIdParameter);
        }
    
        public virtual int VoteResult()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VoteResult");
        }
    }
}
